### ISSUE TITLE
Kubernetes-config file dependent on DB

### ISSUE THREAD

**Issue by raresraf** [raresraf/rafMetrics#18]
Make sure DB-dependent pods starts after DB

**Comment by MoneaVlad** [comment]
:eyes:

**Comment by raresraf** [comment]
@MoneaVlad any status update?

**Comment by raresraf** [comment]
@MoneaVlad any status update?

**Comment by raresraf** [comment]
@MoneaVlad any updates on this?

**Comment by MoneaVlad** [comment]
WIPPe 2 sept. 2020 10:22, Rares Folea <notifications@github.com> a scris:
@MoneaVlad any updates on this?

**Comment by raresraf** [comment]
@MoneaVlad any updates on this?

**Comment by raresraf** [comment]
@MoneaVlad any updates on this?

**Comment by raresraf** [comment]
@MoneaVlad any status update?

**Comment by raresraf** [comment]
@MoneaVlad any updates on this?
