### ISSUE TITLE
Revamp efficiency calculator

### ISSUE THREAD

**Issue by raresraf** [raresraf/rafMetrics#22]
https://github.com/raresraf/rafMetrics/blob/master/WebMonitoring/API/efficiency_metrics.py

Currently, we do not compute it correctly.

**Comment by Yokojima** [comment]
ook

**Comment by raresraf** [comment]
Ty

**Comment by raresraf** [comment]
@raresraf TODO

**Comment by raresraf** [comment]
@Yokojima any updates on this?
